-- Seed: 3 carreras ULEAM con mallas curriculares
BEGIN;

UPDATE perfiles SET "carreraId" = NULL WHERE "carreraId" IS NOT NULL;
UPDATE proyectos_vinculacion SET "carreraId" = NULL WHERE "carreraId" IS NOT NULL;
UPDATE proyectos_investigacion SET "carreraId" = NULL WHERE "carreraId" IS NOT NULL;
UPDATE temas_titulacion SET "carreraId" = NULL WHERE "carreraId" IS NOT NULL;
UPDATE laboratorios SET "carreraId" = NULL WHERE "carreraId" IS NOT NULL;
UPDATE practicas SET "carreraId" = NULL, "materiaId" = NULL WHERE "carreraId" IS NOT NULL OR "materiaId" IS NOT NULL;
DELETE FROM matriculas;
DELETE FROM faltas;
DELETE FROM silabos;
DELETE FROM informes;
DELETE FROM materias;
DELETE FROM carreras;
ALTER SEQUENCE carreras_id_seq RESTART WITH 1;
ALTER SEQUENCE materias_id_seq RESTART WITH 1;

INSERT INTO carreras (nombre, siglas, facultad, coordinador, activa) VALUES ('Ingeniería Agroindustrial', 'IAgroind', 'Facultad de Ciencias Agropecuarias', 'Por asignar', TRUE);
INSERT INTO carreras (nombre, siglas, facultad, coordinador, activa) VALUES ('Ingeniería Agropecuaria', 'IAgropec', 'Facultad de Ciencias Agropecuarias', 'Por asignar', TRUE);
INSERT INTO carreras (nombre, siglas, facultad, coordinador, activa) VALUES ('Agronegocios', 'AgNeg', 'Facultad de Ciencias Agropecuarias', 'Por asignar', TRUE);

INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Química Inorgánica', 'AGRIND-101', 3, 1, 64, 80, 0, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Fundamentos de Física', 'AGRIND-103', 3, 1, 64, 80, 0, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Metodología de la Investigación', 'PAM-5202', 2, 1, 64, 32, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Cálculo Diferencial', 'PAM-1202', 3, 1, 64, 80, 0, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Introducción a la Agroindustria', 'AGRIND-104', 2, 1, 64, 32, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Cátedra Alfaro', '9901V01-R22', 2, 1, 0, 0, 96, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Química Orgánica', 'PAM-2501', 3, 2, 64, 80, 0, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Física', 'PAM-2212.1', 3, 2, 64, 80, 0, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Estadística', 'PAM-1209', 2, 2, 64, 32, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Cálculo Integral', 'PAM-1202.1', 3, 2, 64, 80, 0, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Biología', 'PAM-2302', 2, 2, 64, 32, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Economía Global', '9901V02-R22', 2, 2, 0, 0, 96, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Química Analítica', 'AGRIND-303', 2, 3, 64, 32, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Termodinámica', 'AGRIND-304', 2, 3, 48, 48, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Diseño Experimental', 'AGRIND-405', 2, 3, 64, 32, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Ecuaciones Diferenciales', 'PAM-1219', 3, 3, 64, 80, 0, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Microbiología', 'PAM-2414', 4, 3, 0, 80, 112, 192, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Innovación, Liderazgo y Emprendimiento', '9901V03-R22', 2, 3, 0, 0, 96, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Análisis Instrumental', 'AGRIND-305', 3, 4, 96, 48, 0, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Cálculos de Ingeniería', 'AGRIND-501', 2, 4, 48, 48, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Investigación Operativa', 'AGRIND-505', 3, 4, 48, 96, 0, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Bromatología', 'AGRIND-404', 2, 4, 32, 32, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Biotecnología', 'AGRIND-502', 2, 4, 32, 32, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Química de los Alimentos', 'AGRIND-401A', 3, 4, 32, 32, 80, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Nutrición', 'AGRIND-402', 2, 5, 48, 48, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Transferencia de Calor', 'AGRIND-701', 2, 5, 48, 48, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Análisis Sensorial', 'AGRIND-803A', 3, 5, 48, 96, 0, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Contabilidad', 'AGRIND-406', 2, 5, 48, 48, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Poscosecha', 'AGRIND-504', 3, 5, 48, 16, 80, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Industrialización de Frutas y Hortalizas', 'AGRIND-503', 3, 5, 32, 32, 80, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Ingeniería de Materiales', 'AGRIND-601', 2, 6, 64, 32, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Industrias Cárnicas', 'AGRIND-707', 4, 6, 32, 32, 128, 192, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Industrias Pesqueras', 'AGRIND-607', 2, 6, 48, 48, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Industrias de Granos y Cereales', 'AGRIND-801', 2, 6, 48, 48, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Industrias de Bebidas', 'AGRIND-506', 2, 6, 48, 48, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Industrias de Aceites y Grasas', 'AGRIND-603', 2, 6, 48, 48, 0, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Marco Legal Agroindustrial', 'AGRIND-1003', 5, 7, 144, 96, 0, 240, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Proyecto Integrador Agroindustrial', 'AGRIND-1007', 3, 7, 96, 48, 0, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Gestión Ambiental', 'AGRIND-804A', 2, 7, 32, 32, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (1, 'Prácticas de Servicio Comunitario II', 'PAM-6301.2', 4, 7, 16, 16, 160, 192, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Biología', 'AGR-101', 3, 1, 48, 32, 64, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Química General', 'AGR-102', 3, 1, 48, 32, 64, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Matemática', 'AGR-103', 3, 1, 64, 16, 64, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Metodología de la Investigación', 'AGR-104', 2, 1, 32, 32, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Introducción a las Ciencias Agropecuarias', 'AGR-105', 2, 1, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Cátedra Alfaro', 'AGR-106', 2, 1, 32, 16, 48, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Botánica General', 'AGR-201', 3, 2, 48, 32, 64, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Química Orgánica', 'AGR-202', 3, 2, 64, 32, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Física', 'AGR-203', 3, 2, 48, 16, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Microbiología', 'AGR-204', 2, 2, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Zoología General', 'AGR-205', 3, 2, 48, 32, 64, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Meteorología', 'AGR-206', 2, 2, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Botánica Sistemática', 'AGR-301', 2, 3, 48, 16, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Ciencias del Suelo', 'AGR-302', 3, 3, 64, 32, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Topografía', 'AGR-303', 2, 3, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Sanidad Vegetal', 'AGR-304', 3, 3, 48, 32, 64, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Anatomía y Fisiología Animal', 'AGR-305', 3, 3, 64, 32, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Economía Global', 'AGR-306', 2, 3, 32, 16, 48, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Fitogenética y Mejoramiento', 'AGR-401', 3, 4, 64, 32, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Construcciones Agropecuarias', 'AGR-402', 3, 4, 48, 32, 64, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Sistemas de Información Geográfica', 'AGR-403', 2, 4, 32, 32, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Nutrición Vegetal', 'AGR-404', 2, 4, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Sanidad Animal', 'AGR-405', 2, 4, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Agroecología y Humedad de Suelos', 'AGR-406', 3, 4, 64, 32, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Innovación, Liderazgo y Emprendimiento', 'AGR-501', 2, 5, 32, 16, 48, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Economía Agropecuaria', 'AGR-502', 3, 5, 48, 32, 64, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Sistemas de Riego y Drenaje', 'AGR-503', 3, 5, 64, 32, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Agroforestería', 'AGR-504', 3, 5, 48, 32, 64, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Métodos Estadísticos y Experimental', 'AGR-505', 2, 5, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Mecanización Agrícola', 'AGR-506', 2, 5, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Fundamentos de la Agricultura', 'AGR-601', 2, 6, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Agricultura de Precisión', 'AGR-602', 3, 6, 48, 16, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Práctica Comunitaria SVCP-VIR001', 'AGR-603', 2, 6, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Pastos y Forrajes', 'AGR-604', 3, 6, 48, 48, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Sistemas de Ciclo Corto', 'AGR-605', 3, 6, 48, 48, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Sistemas de Producción Perenne', 'AGR-606', 2, 6, 48, 16, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Nutrición Animal', 'AGR-701', 2, 7, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Producción Animal', 'AGR-702', 4, 7, 64, 32, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Sistemas de Producción Apícola', 'AGR-703', 3, 7, 48, 32, 64, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Sistemas de Producción Avícola', 'AGR-704', 2, 7, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Sistemas de Especies Menores', 'AGR-705', 2, 7, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Sistemas de Producción Porcícola', 'AGR-706', 2, 7, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Gestión Agropecuaria y Administrativa', 'AGR-801', 2, 8, 48, 16, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Preparación y Presentación de Proyectos', 'AGR-802', 5, 8, 32, 32, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'P.R.', 'P.R.', 2, 8, 32, 32, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Desarrollo Local', 'AGR-803', 2, 8, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Biotecnología', 'AGR-804', 2, 8, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Prácticas Preprofesionales I', 'FIP-6302-1', 4, 8, 16, 16, 160, 192, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Sociología Rural', 'AGR-901', 2, 9, 32, 32, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Prácticas Preprofesionales Agropecuarias', 'AGR-902', 5, 9, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Diseño y Evaluación de Proyectos', 'AGR-903', 2, 9, 32, 32, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Marco Legal Agropecuario', 'AGR-904', 3, 9, 48, 48, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (2, 'Prácticas Preprofesionales II', 'FIP-6302-2', 4, 9, 16, 16, 160, 192, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Biología', 'AGRN-101', 3, 1, 48, 48, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Matemática', 'AGRN-102', 3, 1, 64, 32, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Química', 'AGRN-103', 2, 1, 32, 32, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Introducción a los Negocios Agrícolas', 'AGRN-104', 2, 1, 32, 16, 48, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Cátedra Alfaro', 'INST-CAAL', 2, 1, 32, 32, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Investigación Aplicada a los Negocios Agrícolas', 'AGRN-106', 3, 1, 48, 48, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Botánica', 'AGRN-201', 3, 2, 64, 32, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Matemática Financiera', 'AGRN-202', 2, 2, 32, 16, 48, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Estadística', 'AGRN-203', 3, 2, 48, 32, 64, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Economía Global', 'INST-ECGL', 2, 2, 32, 32, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Agricultura Alternativa y Colaborativa', 'AGRN-205', 2, 2, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Ciencias del Suelo', 'AGRN-206', 3, 2, 64, 32, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Contabilidad Agrícola', 'AGRN-301', 3, 3, 48, 48, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Administración de la Producción', 'AGRN-302', 2, 3, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Legislación y Política Nacional', 'AGRN-303', 3, 3, 48, 48, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Sistemas Pecuarios y Acuicultura', 'AGRN-304', 2, 3, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Sistemas de Producción Agrícola', 'AGRN-305', 3, 3, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Optimización del Riego', 'AGRN-306', 2, 3, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Contabilidad Financiera', 'AGRN-401', 3, 4, 48, 48, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Teoría Macro y Microeconómica', 'AGRN-402', 2, 4, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Emprendimiento, Innovación y Creatividad', 'INST-INEL', 2, 4, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Biotecnología Agrícola', 'AGRN-404', 4, 4, 48, 48, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Manejo Postcosecha', 'AGRN-405', 2, 4, 48, 16, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Sistemas de Información Geográfica', 'AGRN-406', 2, 4, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Economía Agrícola', 'AGRN-501', 2, 5, 48, 16, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Prácticas Comunitarias de Servicio', 'AGRN-502', 2, 5, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Inventarios y Cadena de Suministro', 'AGRN-503', 3, 5, 64, 32, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Gerencia Financiera', 'AGRN-504', 2, 5, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Sistemas Agroindustriales', 'AGRN-505', 3, 5, 48, 48, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Agricultura de Precisión', 'AGRN-506', 2, 5, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Economía Solidaria Popular', 'AGRN-601', 2, 6, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Prácticas Comunitarias de Servicio II', 'AGRN-602', 4, 6, 48, 48, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Bioproductos y Biocomercio', 'AGRN-603', 3, 6, 48, 48, 48, 144, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Bioeconomía', 'AGRN-604', 2, 6, 48, 16, 32, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Técnicas de Negociación', 'AGRN-605', 2, 6, 48, 32, 16, 96, TRUE);
INSERT INTO materias ("carreraId", nombre, codigo, creditos, nivel, acd, ape, aa, horas, activa) VALUES (3, 'Desarrollo Territorial Rural', 'AGRN-606', 2, 6, 48, 16, 32, 96, TRUE);

COMMIT;
